# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  testProjects: '**/[Tt]ests?/*.csproj'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.0.100'
  inputs:
    packageType: 'sdk'
    version: '3.0.100'

- task: NodeTool@0
  displayName: 'Use Node 10.16.x'
  inputs:
    versionSpec: 10.16.x
  enabled: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: true
    customCommand: 'install -g windows-build-tools'
  enabled: false

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: 'Use Yarn 1.x'
  inputs:
    checkLatest: true

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn install'
  inputs:
    ProjectDirectory: src/SurveyApp/ClientApp
    Arguments: install

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud SurveyApp'
    organization: 'adaskothebeast-github'
    projectKey: 'AdaskoTheBeAsT_SurveyApp'
    projectName: SurveyApp
    arguments: '/d:sonar.cs.vstest.reportsPaths="*/TestResults/.trx" /v:"2.0"'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    arguments: 'SurveyApp.sln --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage" --logger:"trx;LogFileName=backend-results.trx"'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'


- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
